# Generated by Django 4.0.4 on 2022-05-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
