# Generated by Django 4.0.4 on 2022-05-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_app', '0002_alter_city_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
