# Generated by Django 4.0.4 on 2022-05-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_app', '0004_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.IntegerField(default=0),
        ),
    ]
