# Generated by Django 4.0.4 on 2022-05-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart_app', '0006_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='counter',
        ),
    ]
