# Generated by Django 4.0.4 on 2022-05-22 10:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chart_app', '0007_remove_event_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 10, 46, 27, 158217, tzinfo=utc)),
        ),
    ]
