# Generated by Django 4.0.4 on 2022-05-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart_app', '0009_alter_event_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_at',
            new_name='date_create',
        ),
    ]
