# Generated by Django 4.0.4 on 2022-05-22 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chart_app', '0011_alter_event_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 10, 57, 30, 498853, tzinfo=utc)),
        ),
    ]
