# Generated by Django 4.0.4 on 2022-05-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_app', '0012_alter_event_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
